#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend lGikundiro-frontend
        bind *:80
        mode http
        default_backend lGikundiro-backend
        timeout client 30s
backend lGikundiro-backend
        mode http 
        balance roundrobin
        server 54.221.174.188:80 check
        server 34.226.191.18:80 check
        timeout connect 30s
        timeout server 30s
"
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo service haproxy restart
